### PR TITLE
Update CI config

### PR DESCRIPTION
**Pull request by avitex**
Adapted from what you have here: https://github.com/sfackler/r2d2/blob/master/.circleci/config.yml

### CODE REVIEW

**Comment by sfackler** [comment]
The current circle config should work, but builds aren't triggering for some reason. Probably better to switch over to github actions instead: https://github.com/sfackler/staged-builder/blob/develop/.github/workflows/ci.yml

**Comment by avitex** [comment]
I'll update accordingly for you :) Thanks for the prompt responses

**Comment by avitex** [comment]
I'll note `--all` is now `--workspace` if you want to update on that repo

**Comment by avitex** [comment]
Okay, updated for Github actions now

**Pull request merged**
